import { Callout } from "nextra-theme-docs";

## Dockerfilelar yozish bo'yicha qo'llanma

![docker](/images/tutorials/container/4.png)


Docker samaradorligining markazida **Dockerfile** yotadi - Docker imagelarini yaratish uchun ishlatiladigan asosiy skript. Ushbu fayllar takrorlanadigan va portativ konteynerli muhitni yaratish uchun zarur bo'lgan ko'rsatmalar va bog'liqliklarni qamrab oladi. O'rnatish jarayonini soddalashtirish va turli muhitlarda izchillikni ta'minlashga intilayotgan dasturchilar va DevOps muhandislari uchun samarali Dockerfilelarni qanday yaratishni tushunish juda muhimdir.

Ushbu qo'llanma Dockerfilelar qanday yozishni uni elementlarini ko'rib chiqamiz.

### FROM

Dockerfiledagi `FROM` instructioni sizning imagengiz asosida quriladigan asosiy imageni belgilash uchun ishlatiladi. Bu yangi konteyner imegaseni yaratish uchun boshlang'ich nuqtadir. Docker iamgeni yaratishni boshlaganingizda, odatda uni ma'lum muhit yoki funksiyalar to'plamini ta'minlaydigan mavjud imagega asoslashni xohlaysiz. `FROM` instructioni ushbu asosiy imageni belgilaydi.

```bash /FROM/
FROM <image>[:<tag>] [@<digest>]
#NodeJS namunalar
FROM node
FROM node:18
FROM node@sha256:XXXXXX
```

**image** - bu yangi imagengizga asoslanmoqchi bo'lgan imagening nomi.

**tag** (ixtiyoriy) imagening muayyan versiyasi yoki variantini bildiradi. Agar belgilanmagan bo'lsa, u default bo'yicha `latest` bo'ladi.

**@digest** (ixtiyoriy) sizga imageni uning content hashi (digest) bo'yicha belgilash imkonini beradi va bu imagega aniq mos kelishini ta'minlaydi.

### MAINTAINER, LABEL

Dockerfile-dagi `MAINTAINER` instructioni qurilayotgan imagening muallifi yoki maintainerini ko'rsatish uchun ishlatilgan. Biroq, bu instruction iamge haqidagi metamaʼlumotlar, jumladan, texnik maʼlumotlar bilan taʼminlash uchun `LABEL` dan foydalanish foydasiga eskirgan.

Maintainerni ko'rsatish uchun `LABEL` dan qanday foydalanish mumkinligiga misol:

```bash /MAINTAINER/ /LABEL/
FROM node:18
MAINTAINER Otabek Ismoilov
# LABEL bilan
LABEL maintainer="Otabek Ismoilov ismoilovdev@gmail.com"
```

### RUN

Docker faylidagi `RUN` buyrug'i Docker imagedagi buyruqlarni bajarish uchun ishlatiladi. Ushbu buyruqlar odatda paketlarni o'rnatish, tizimni yangilash, fayllarni yuklab olish yoki konteyner ichidagi muhitni tayyorlash uchun zarur bo'lgan boshqa vazifalar uchun ishlatiladi.

`RUN` qanday ishlatilishiga misol:

```bash /RUN/
FROM ubuntu:latest

# Konteynerni yangilash va konteynerga zip, git, unzip o'rnatish
RUN apt-get update && apt-get install -y \
    zip \
    git \
    unzip
```

Javascript applicationlar uchun misol

```bash /RUN/
FROM node:18

RUN npm install
RUN npm build
```
### WORKDIR

Dockerfiledagi `WORKDIR` ko'rsatmasi Dockerfiledagi har qanday keyingi ko'rsatmalar uchun ishchi jildni o'rnatish uchun ishlatiladi. Bu buyruqlar bajariladigan konteyner ichidagi joriy jildni o'zgartiradi.

WORKDIR ga misol:

```bash /WORKDIR/
FROM python:3.9-slim
WORKDIR /usr/src/app
```
`WORKDIR /usr/src/app` Bu qator konteyner ichidagi ishchi jildni `/usr/src/app` ga o'rnatadi. Dockerfile-dagi keyingi buyruqlar, agar bekor qilinmasa, ushbu ko'rsatilgan jildda bajariladi.

Ishchi jildi o'rnatish, ayniqsa, fayllarda ishlaydigan yoki yo'llarga(path) murojaat qilish kerak bo'lgan buyruqlar har safar to'liq yo'lni ko'rsatmasdan doimiy ishlashini ta'minlash uchun foydalidir. Shuni ta'kidlash kerakki, WORKDIR-dan foydalanish, agar asosiy imageda mavjud bo'lmasa, jild yaratmaydi. Agar ko'rsatilgan jildg imageda mavjud bo'lmasa, Docker uni buyruq talab qilganda yoki `COPY` ko'rsatmasi yordamida ushbu jildga fayllar ko'chirilganda yaratadi.


### COPY

Dockerfiledagi `COPY` buyrug'i fayllar yoki jildlarni host mashinasidan qurilayotgan Docker imagesiga nusxalash uchun ishlatiladi.

`COPY` qanday ishlatilishiga misol:

```bash /COPY/
FROM ubuntu:latest
RUN mkdir /myapp

COPY app-files /myapp
```

app-files jildidagi fayllarni host mashinasidan iamge ichidagi /myapp jildiga ko'chiradi.

Python applicationlari uchun real namuna

```bash /COPY/
FROM python:3.9-slim
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
```
`WORKDIR` konteyner ichidagi ishni jildni `/usr/src/app` ga o'rnatadi. `COPY` Joriy jilddagi barcha fayllarni Docker imagedagi `/usr/src/app` jildiga ko'chiradi.

### ENV

Dockerfiledagi `ENV` buyrug'i konteyner ichidagi muhit o'zgaruvchilarini(environment variable) o'rnatish uchun ishlatiladi. Ushbu o'zgaruvchilar key-value juftliklari bo'lib, ularga konteyner ichida ishlaydigan har qanday jarayon orqali kirish mumkin.

`ENV` insturctionlaridan foydalanishni ko'rsatadigan oddiy Dockerfile misoli:

```bash /ENV/
FROM node:14

ENV NODE_ENV=production
ENV PORT=3000
```
Real mysql database uchun `ENV` ishlatilishi

```bash /ENV/
FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=my-secret-pw
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
```

### ADD

Dockerfile-dagi `ADD` insturctioni fayllarni, jildlarni yoki masofaviy URL-larni yaratish kontekstidan yaratilayotgan Docker imagening fayl tizimiga nusxalash uchun ishlatiladi. Bu sizga Docker build kontekstidan (Dockerfile joylashgan jild) local fayllar yoki jildlarni imagega qo'shish imkonini beradi.

`ADD` insturctioni sintaksisi quyidagicha:

```bash /ADD/
FROM node:14

ADD myapp /usr/src/app
```
Bu yerda Docker build kontekstidan `myapp` nomli local jildni image ichidagi `/usr/src/app` jildiga qo'shiladi.

Masofaviy fayl qo'shsih quyidagicha

```bash /ADD/
FROM python:3.9

ADD https://example.com/file.txt /app/file.txt
```
`ADD` insturctioni, shuningdek, masofaviy(remote) URL-manzillardan fayllarni olib, ularni imagega qo'shishi mumkin. Ushbu misolda fayl (file.txt) `https://example.com/file.txt` dan yuklab olinadi va imagening `/app` katalogiga joylashtiriladi.

### CMD

`CMD`  insturctioni ushbu Docker imagega asoslangan konteyner ishga tushirilganda bajarilishi kerak bo'lgan buyruqni belgilash uchun ishlatiladi. U konteyner ishga tushganda ishga tushirish uchun standart buyruqni belgilaydi, garchi uni konteynerni ishga tushirishda buyruq berish orqali bekor qilish mumkin.

CMD insturctioni sintaksisi quyidagicha:

```bash /CMD/
FROM python:3.9

CMD ["python", "app.py"]
```
Ushbu misolda, ushbu imagega asoslangan konteyner ishga tushirilganda, u standart buyruq sifatida Python skripti `app.py` ni ishga tushiradi.

Web Serverni ishga tushirishga misol

```bash
FROM nginx:latest

CMD ["nginx", "-g", "daemon off;"]
```
Bu yerda CMD instructioni Nginx veb-serverini konteyner ichida ishga tushirish buyrug'ini belgilaydi.

### ENTRYPOINT

`ENTRYPOINT` instructioni Docker imagedan konteyner ishga tushirilganda bajariladigan asosiy buyruqni o'rnatadi. Runtimeda buyruq berish orqali bekor qilinishi mumkin bo'lgan `CMD` instructionidan farqli o'laroq, `ENTRYPOINT` konteynerning bajarilishi(execute) uchun belgilangan boshlanish nuqtasini ta'minlaydi, ammo konteyner ishga tushirilganda u hali ham qo'shimcha argumentlar yoki buyruqlar bilan to'ldirilishi mumkin.

`ENTRYPOINT` instructioni sintaksisi `CMD` ga o'xshaydi:

```bash /ENTRYPOINT/
FROM python:3.9

ENTRYPOINT ["python", "app.py"]
```
Bunday holda, `ENTRYPOINT` instructioni konteyner ishga tushirilganda Python skripti `app.py` ni asosiy buyruq sifatida bajarishi(execute) kerakligini bildiradi.

CMD bilan birga ishlatilishi

```bash /ENTRYPOINT/ /CMD/
FROM nginx:latest

ENTRYPOINT ["nginx", "-g", "daemon off;"]
CMD ["-c", "/etc/nginx/nginx.conf"]
```

Ushbu Dockerfile Nginx serverini standart sozlamalar bilan ishga tushirish uchun `ENTRYPOINT`-dan foydalanadi va foydalaniladigan konfiguratsiya faylini belgilash uchun `CMD`-dan foydalanadi (nginx.conf). Konteyner ishga tushganda, ENTRYPOINT standart sozlamalar bilan Nginx-ni ishga tushiradi va CMD konfiguratsiya fayli argumentini taqdim etish orqali uni to'ldiradi.

ENTRYPOINT konteynerning asosiy ishlashini aniqlash va izchil bajarilish muhitini ta'minlash uchun foydalidir. U ko'pincha ma'lum bir boshlang'ich nuqtasi yoki ishga tushirish jarayonini talab qiladigan uzoq muddatli servicelar yoki ilovalar uchun qo'llaniladi. Bundan tashqari, u foydalanuvchilarga iruntimeda qo'shimcha argumentlar yoki buyruqlar taqdim etish imkonini beradi va uning funksiyalarini kengaytiradi.

### EXPOSE

`EXPOSE` insturctioni Dockerga konteyner runtimeda ma'lum tarmoq portlarini tinglashi(listen) haqida xabar berish uchun ishlatiladi. Biroq, u portlarni publish qilmaydi yoki ochmaydi. U foydalanuvchilar uchun konteyner qaysi portlarni tinglamoqchi(listen) ekanligini tushunish uchun documentatsiya sifatida xizmat qiladi.

`EXPOSE` insturctionining sintaksisi oddiy:

```bash /EXPOSE/
FROM nginx:latest

# HTTP trafigi uchun 80 portini ochadi(expose)
EXPOSE 80
```

Bunday holda, `EXPOSE` insturctioni Dockerga konteyner kiruvchi trafik uchun `80`-portni tinglashini(listen) aytadi. Biroq, bu insturctionning o'zi portni host machinega publish qilmaydi yoki uni mapda ko'rsatmaydi. Portlarni konteynerdan hostga map qilish yoki publish qilish uchun konteynerni `docker run -p` buyru'gidan foydalanishingiz kerak.

Masalan, konteynerning `80`-portini host-mashinadagi `8080`-portga map qilish uchun siz konteynerni quyidagicha ishga tushirasiz:

```bash /-p/
docker run -p 8080:80 my_image
```

Bu buyruq Docker-ga `80`-portni konteynerdan hostdagi `8080`-portga publish qilishni aytadi, bu esa konteyner ichida ishlaydigan servicelarga tashqi kirish imkonini beradi.

`EXPOSE` konteyner qaysi portlardan foydalanishni kutayotganini bildirish uchun ko'proq qo'llanma xususiyatidir. Bu foydalanuvchilarga runtimeda konteynerning tarmoq harakatiga bevosita ta'sir qilmasdan mo'ljallangan tarmoq aloqa portlarini tushunishga yordam beradi. Haqiqiy port ulanishi va tarmoq konfiguratsiyasi konteyner tegishli port mapping bilan `docker run` buyrug'i yordamida ishga tushirilganda amalga oshiriladi.

Misol uchun NodeJS dasturiga namuna Dockerfile

```bash /EXPOSE/
FROM node:14

WORKDIR /usr/src/app

# package.json va package-lock.json fayllaridan nusxa oladi
COPY package*.json ./

# Dependencilarniu o'rnatadi
RUN npm install

# Ilova fayllarini nusxalaydi
COPY . .

# Node.js ilovasi uchun 3000 portini ochadi
EXPOSE 3000

# Node.js ilovasini ishga tushirish buyrug'i
CMD ["npm", "start"]
```
Ushbu Node.js misolida `EXPOSE` insturctioni konteyner ichidagi Node.js ilovasi `3000`-portda tinglashini(listen) bildiradi. Bu ko‘plab Node.js ilovalari uchun umumiy senariy bo‘lishi mumkin, chunki ular odatda ushbu portdan default bo‘yicha foydalanadilar.